# Generated by Django 5.0.3 on 2024-03-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=255)),
                ('ticket_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_type', models.CharField(choices=[('sleeper', 'Sleeper'), ('semisleeper', 'Semi-sleeper'), ('sitting', 'Sitting')], max_length=20)),
                ('noofseats', models.IntegerField()),
                ('pickup', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('provisions', models.CharField(choices=[('waterbottle', 'Water Bottle'), ('vegmeals', 'Veg Meal'), ('nonvegmeals', 'Non-Veg Meal')], max_length=20)),
            ],
        ),
    ]
